Adds DOT projected precipitation into ArcticEDS
ua-snap/arctic-eds pull request #290
Opened 2023-08-15 20:18 UTC by BobTorgerson

This PR adds the projected precipitation data that had been generated for the Department of Transportation into the precipitation section of the ArcticEDS report. This generates a table very similar to the table generated on the [original website](https://snap.uaf.edu/tools/future-alaska-precip) but at a much faster rate coming from Rasdaman and the data API. 

To use this branch, use these environment variables:

export RASDAMAN_URL=https://apollo.snap.uaf.edu/rasdaman/ows
export SNAP_API_URL=http://localhost:5000

Closes #289

2023-08-15 23:57 UTC, cstephen requested changes
This PR looks good and works as expected against the corresponding data-api branch. I noticed one small `console.log` statement that should be removed, but otherwise this looks good to go!

2023-08-15 23:57 UTC, cstephen commented on components/reports/ProjectedPrecipitation.vue
> +      console.log('Fetching...')
```suggestion
```

2023-08-16 00:03 UTC, cstephen approved these changes

2023-08-28 22:23 UTC, brucecrevensten approved these changes
I think this looks good!  I vote for merging it as-is, and handling further updates via other smaller PRs.

2023-08-28 22:23 UTC, merged